/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'me.ricciuti.dreams.dream'

export { $nsid }

/** A single entry in the dream diary: a real dream, written down, paired with an image generated from it. */
type Main = {
  $type: 'me.ricciuti.dreams.dream'

  /**
   * The dream's title.
   */
  title: string

  /**
   * The date the dream was dreamed, as YYYY-MM-DD.
   */
  date: string

  /**
   * The generated dream image.
   */
  image: l.BlobRef

  /**
   * Width component of the image aspect ratio.
   */
  aspectWidth: number

  /**
   * Height component of the image aspect ratio.
   */
  aspectHeight: number

  /**
   * One line the dream said, shown in the serif voice.
   */
  fragment: string

  /**
   * Alt text for the image, written the way the diary would describe it.
   */
  alt: string

  /**
   * The whole story, one item per paragraph.
   */
  story: string[]

  /**
   * When this entry was logged.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** A single entry in the dream diary: a real dream, written down, paired with an image generated from it. */
const main = /*#__PURE__*/ l.record<'any', Main>(
  'any',
  $nsid,
  /*#__PURE__*/ l.object({
    title: /*#__PURE__*/ l.string({ maxLength: 1280, maxGraphemes: 128 }),
    date: /*#__PURE__*/ l.string({ minLength: 10, maxLength: 10 }),
    image: /*#__PURE__*/ l.blob({ accept: ['image/*'], maxSize: 5000000 }),
    aspectWidth: /*#__PURE__*/ l.integer({ minimum: 1 }),
    aspectHeight: /*#__PURE__*/ l.integer({ minimum: 1 }),
    fragment: /*#__PURE__*/ l.string({ maxLength: 2560, maxGraphemes: 256 }),
    alt: /*#__PURE__*/ l.string({ maxLength: 5120 }),
    story: /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ maxLength: 20480 })),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
